
apiVersion: v1
kind: Service
metadata:
  name: backend-mlops-dc
  labels:
    app: mlops-app
spec:
  selector:
    app: mlops-app
    deploymentconfig: backend-mlops
  ports:
    - name: backend-mlops
      port: 5000